[build]
  command = "npm run build"
  publish = "dist"

# Headers for JSON files to ensure correct MIME type
[[headers]]
  for = "/data/*.json"
  [headers.values]
    Content-Type = "application/json"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
